server:
  port: 9500
logging:
  level:
    org.springframework.cloud.gateway: TRACE
spring:
  application:
    name: openyich-gateway
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://httpbin.org
        predicates:
        - Path=/get