server:
  port: 9500
logging:
  level:
    org.springframework.cloud.gateway: TRACE
openyich:
  gateway:
    security:
      jwt:
        secret: 0ddf5597e02d981f8803c4cc11f015a4e52679d706edb29b595d9e466def5bcf95273a3053ab5d97ee893c23e4023b912daefaade316406a33b7685d4d223dfa
spring:
  application:
    name: openyich-gateway
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://httpbin.org
        predicates:
        - Path=/get